# Generated by Django 5.0 on 2026-09-29 15:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('precio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Precio')),
                ('categoria', models.CharField(choices=[('python', 'Python'), ('web', 'Web'), ('bots', 'Bots'), ('ui', 'Plantillas UI'), ('otros', 'Otros')], default='otros', max_length=20, verbose_name='Categoría')),
                ('activo', models.BooleanField(default=True, help_text='Si lo desmarcas, no se mostrará en la tienda.', verbose_name='Publicado')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
