# Generated by Django 5.0 on 2026-09-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.PositiveIntegerField(blank=True, help_text='Déjalo vacío si no está en oferta.', null=True, verbose_name='Precio de oferta'),
        ),
    ]
