# Generated by Django 5.0 on 2026-09-30 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_precio_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=10, help_text='Unidades disponibles. Si queda en 0 se muestra como «Stock agotado».', verbose_name='Stock'),
        ),
    ]
